variables:
  GIT_SUBMODULE_STRATEGY: recursive
  REGISTRY: registry.teonite.net

default:
  tags:
    - kubernetes

stages:
  - build

.build-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${REGISTRY}\":{\"username\":\"${REGISTRY_USER}\",\"password\":\"${REGISTRY_SECRET}\"}}}" > /kaniko/.docker/config.json

build_master:
  stage: build
  only:
    - master
  script:
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/Dockerfile
      --destination ${REGISTRY}/defguard/${CI_PROJECT_NAME}:${CI_PIPELINE_ID}
      --destination ${REGISTRY}/defguard/${CI_PROJECT_NAME}:latest


build:
  extends: .build-image
  script:
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/Dockerfile
      --destination ${REGISTRY}/defguard/${CI_PROJECT_NAME}:${CI_PIPELINE_ID}
      --single-snapshot
  except:
    - master

