vulnerabilities:
  - id: CVE-2025-69720
    expired_at: 2026-10-31
    statement: "No fixed version available in debian:13-slim: waiting for ncurses patch"
  - id: CVE-2026-76642
    expired_at: 2026-10-31
    statement: "No fixed version available in debian:13-slim: waiting for bsdutils patch"
  - id: CVE-2026-78408
    expired_at: 2026-10-31
    statement: "No fixed version available in debian:13-slim: waiting for bsdutils patch"
  - id: CVE-2026-78409
    expired_at: 2026-10-31
    statement: "No fixed version available in debian:13-slim: waiting for bsdutils patch"
  - id: CVE-2026-78410
    expired_at: 2026-10-31
    statement: "No fixed version available in debian:13-slim: waiting for bsdutils patch"
  - id: CVE-2026-54369
    expired_at: 2026-10-31
    statement: "No fixed version available in debian:13-slim: waiting for libacl1 patch"
  - id: CVE-2026-9538
    expired_at: 2026-10-31
    statement: "No fixed version available in debian:13-slim: waiting for libperl5.40 patch"
  - id: CVE-2026-16742
    expired_at: 2026-10-31
    statement: "No fixed version available in debian:13-slim: waiting for libsystemd0 patch"
