[package]
name = "defguard-gateway"
version = "2.1.0"
edition = "2024"
rust-version = "1.96"

[dependencies]
axum = "0.8"
base64 = "0.23"
chrono = "0.4"
clap = { version = "4.6", features = ["derive", "env"] }
defguard_certs = { git = "https://github.com/DefGuard/defguard.git", rev = "cdf3ef9a70796d47a6247ad1300d2e6bb7474cf5" }
defguard_grpc_tls = { git = "https://github.com/DefGuard/defguard.git", rev = "cdf3ef9a70796d47a6247ad1300d2e6bb7474cf5" }
defguard_version = { git = "https://github.com/DefGuard/defguard.git", rev = "cdf3ef9a70796d47a6247ad1300d2e6bb7474cf5" }
defguard_wireguard_rs = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring"] }
rustls-pki-types = "1"
rustls-webpki = { version = "0.103", features = ["ring", "std"] }
env_logger = "0.11"
ipnetwork = "0.21"
libc = { version = "0.2", default-features = false }
log = "0.4"
prost = "0.14"
prost-types = "0.14"
serde = { version = "1.0", features = ["derive"] }
syslog = "7.0"
thiserror = "2.0"
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread", "signal", "sync", "time"] }
tokio-stream = { version = "0.1", features = [] }
toml = { version = "1.0", default-features = false, features = [
    "parse",
    "serde",
] }
tonic = { version = "0.14", default-features = false, features = [
    "codegen",
    "gzip",
    "router",
    "tls-native-roots",
    "tls-ring",
] }
tonic-prost = "0.14"
tower = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"

[target.'cfg(target_os = "linux")'.dependencies]
nftnl = "0.9"
mnl = "0.3"

[dev-dependencies]
tokio = { version = "1", features = ["net"] }
tonic = { version = "0.14", default-features = false, features = [
    "codegen",
    "router",
    "transport",
] }
x25519-dalek = { version = "3.0", features = ["getrandom", "static_secrets"] }

[build-dependencies]
tonic-prost-build = "0.14"
vergen-git2 = "10.0"

[profile.release]
codegen-units = 1
panic = "abort"
lto = "thin"
strip = "symbols"
