[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/defguard/cross:x86_64-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/defguard/cross:armv7-unknown-linux-gnueabihf"

[target.x86_64-unknown-freebsd]
pre-build = ["pkg install -y protobuf"]
