[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes unzip libnftnl-dev:$CROSS_DEB_ARCH libmnl-dev:$CROSS_DEB_ARCH",
    "ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/libnftnl.pc /usr/lib/pkgconfig/libnftnl.pc",
    "ln -sf /usr/lib/x86_64-linux-gnu/pkgconfig/libmnl.pc /usr/lib/pkgconfig/libmnl.pc",
    "PB_REL='https://github.com/protocolbuffers/protobuf/releases'",
    "PB_VERSION='3.20.0' && curl -LO $PB_REL/download/v$PB_VERSION/protoc-$PB_VERSION-linux-x86_64.zip",
    "unzip protoc-$PB_VERSION-linux-x86_64.zip bin/protoc include/google/* -d /usr",
]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes unzip libnftnl-dev:$CROSS_DEB_ARCH libmnl-dev:$CROSS_DEB_ARCH",
    "PB_REL='https://github.com/protocolbuffers/protobuf/releases'",
    "PB_VERSION='3.20.0' && curl -LO $PB_REL/download/v$PB_VERSION/protoc-$PB_VERSION-linux-x86_64.zip",
    "unzip protoc-$PB_VERSION-linux-x86_64.zip bin/protoc include/google/* -d /usr",
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes unzip libnftnl-dev:$CROSS_DEB_ARCH libmnl-dev:$CROSS_DEB_ARCH",
    "ln -sf /usr/lib/aarch64-linux-gnu/pkgconfig/libnftnl.pc /usr/lib/pkgconfig/libnftnl.pc",
    "ln -sf /usr/lib/aarch64-linux-gnu/pkgconfig/libmnl.pc /usr/lib/pkgconfig/libmnl.pc",
    "PB_REL='https://github.com/protocolbuffers/protobuf/releases'",
    "PB_VERSION='3.20.0' && curl -LO $PB_REL/download/v$PB_VERSION/protoc-$PB_VERSION-linux-x86_64.zip",
    "unzip protoc-$PB_VERSION-linux-x86_64.zip bin/protoc include/google/* -d /usr",
]

[target.x86_64-unknown-freebsd]
pre-build = [
    "apt-get update && apt-get install --assume-yes unzip",
    "PB_REL='https://github.com/protocolbuffers/protobuf/releases'",
    "PB_VERSION='3.20.0' && curl -LO $PB_REL/download/v$PB_VERSION/protoc-$PB_VERSION-linux-x86_64.zip",
    "unzip protoc-$PB_VERSION-linux-x86_64.zip bin/protoc include/google/* -d /usr",
]
