PLUGIN_NAME=     defguard-gateway
PLUGIN_VERSION=        1.0
PLUGIN_COMMENT=        Gateway service for defguard
#PLUGIN_DEPENDS=
PLUGIN_MAINTAINER= defguard@community.net

.include "../../Mk/plugins.mk"
