#!/bin/sh

# PROVIDE: defguard-gateway
# REQUIRE: NETWORKING wireguard
# KEYWORD: shutdown

. /etc/rc.subr

name="defguard_gateway"
rcvar=defguard_gateway_enable
command="/usr/local/sbin/defguard-gateway"
config="/etc/defguard/gateway.toml"
start_cmd="${name}_start"

defguard_gateway_start()
{
  ${command} --config ${config} &
}

load_rc_config $name
run_rc_command "$1"
