# NOTE: must replace default with actual value
token = "{{ OPNsense.defguardgateway.general.Token|default("") }}"
# Required: defguard server gRPC endpoint URL
# NOTE: must replace default with actual value
grpc_url = "{{ OPNsense.defguardgateway.general.GrpcUrl|default("") }}"
# Optional: gateway name which will be displayed in defguard web UI
name = "{{ OPNsense.defguardgateway.general.Name|default("Gateway A") }}"
# Required: use userspace WireGuard implementation (e.g. wireguard-go)
{% if OPNsense.defguardgateway.general.Userspace == "1" %}
userspace = true
{% else %}
userspace = false
{% endif %}
# Optional: path to TLS cert file
{% if not helpers.empty('OPNsense.defguardgateway.general.GrpcCertPath') %}
grpc_ca = "{{ OPNsense.defguardgateway.general.GrpcCertPath }}"
{% endif %}
# Required: how often should interface stat updates be sent to defguard server (in seconds)
stats_period = {{ OPNsense.defguardgateway.general.StatsPeriod|default(60) }}
# Required: name of WireGuard interface
ifname = "{{ OPNsense.defguardgateway.general.IfName|default("wg0") }}"
# Optional: write PID to this file
{% if not helpers.empty('OPNsense.defguardgateway.general.PidFile') %}
pidfile = "{{ OPNsense.defguardgateway.general.PidFile }}"
{% endif %}
# Required: enable logging to syslog
{% if OPNsense.defguardgateway.general.UseSyslog == "1" %}
use_syslog = true
{% else %}
use_syslog = false
{% endif %}
# Required: which syslog facility to use
syslog_facility = "{{ OPNsense.defguardgateway.general.SyslogFacility|default("LOG_USER") }}"
# Required: which socket to use for logging
syslog_socket = "{{ OPNsense.defguardgateway.general.SyslogSocket|default("/var/run/log") }}"

{% if not helpers.empty('OPNsense.defguardgateway.general.PreUp') %}
pre_up = "{{ OPNsense.defguardgateway.general.PreUp }}"
{% endif %}

{% if not helpers.empty('OPNsense.defguardgateway.general.PreDown') %}
pre_down = "{{ OPNsense.defguardgateway.general.PreDown }}"
{% endif %}

{% if not helpers.empty('OPNsense.defguardgateway.general.PostUp') %}
post_up = "{{ OPNsense.defguardgateway.general.PostUp }}"
{% endif %}

{% if not helpers.empty('OPNsense.defguardgateway.general.PostDown') %}
post_down = "{{ OPNsense.defguardgateway.general.PostDown }}"
{% endif %}
