name: Build current image
on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  build-current:
    uses: ./.github/workflows/build-docker.yml
    with:
      tags: |
        type=raw,value=current
        type=ref,event=branch
        type=sha
