name: Periodic SBOM Regeneration

on:
  schedule:
    - cron: '30 2 * * *' # 2:30 AM UTC

jobs:
  list-releases:
    name: List Existing Releases
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.get-releases.outputs.releases }}
    steps:
      - name: Get list of releases
        id: get-releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASES_JSON=$(gh api repos/${{ github.repository }}/releases \
            --jq '[.[] | select(.draft == false) | {tagName: .tag_name, uploadUrl: .upload_url}][:3]')
          echo "releases=$RELEASES_JSON" >> $GITHUB_OUTPUT

  # This job will create a parallel run for each release found by the previous job.
  regenerate-for-release:
    name: Regenerate SBOM for Release
    needs: list-releases
    # Don't run this job if there are no releases to process
    if: needs.list-releases.outputs.releases != '[]'
    strategy:
      fail-fast: false
      # Dynamically create a matrix from the JSON output of the 'list-releases' job
      matrix:
        release: ${{ fromJson(needs.list-releases.outputs.releases) }}
    uses: ./.github/workflows/sbom.yml
    with:
      upload_url: ${{ matrix.release.uploadUrl }}
      tag: ${{ matrix.release.tagName }}
    secrets: inherit
